id: IFEF0F606
ocr_import_info:
  timestamp: '2023-06-24T04:45:43.703927+00:00'
  batch_id: batch-0550
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-24 04:56:29.512239+00:00
last_modified: 2023-06-24 04:56:29.512246+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4976
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4976
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་དང་བཞི་བརྒྱ་པ་དབུ་མ་རྒྱན་བཅས།
  languages:
  - bo
  author: མཁན་ཆེན་ཞི་བ་འཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9984162573677677
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN4978:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4978
      total_pages: 118
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4978.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9984162573677677
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
